### ISSUE TITLE
Bugs on Sign up page

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/docs#2]
[How to Sign Up page](http://docs.democracyos.org/tutorials/sign-up.html) has two errors:
- [ ] All items in the ordered list begins with `1.`. Each one is a separated `<ol>`:
  ![image](https://cloud.githubusercontent.com/assets/4335188/10554392/94c3b35a-7439-11e5-96df-6ef7902829a7.png)
- [ ] Last image is broken:
  ![image](https://cloud.githubusercontent.com/assets/4335188/10554403/b9269d98-7439-11e5-80fb-fe99e96c4677.png)

**Comment by mjlescano** [comment]
Moved this issue here: https://github.com/DemocracyOS/app/issues/1082, as this is an error on the documentation itself. Not on the `docs` page.
